### PR TITLE
[TECHNICAL SUPPORT] LPS-56153 Wrong profile pictures in workflow notifications

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-56153

Hi Marcellus,

The pattern that Norbi have reused can be found in https://github.com/liferay/liferay-plugins/blob/master/webs/kaleo-web/docroot/WEB-INF/src/com/liferay/portal/workflow/kaleo/runtime/notification/TemplateNotificationMessageGenerator.java#L116-139

However, we are not sure that a KaleoTaskInstanceToken can ever be null when sending notifications.

Thanks,
Tibi

/cc @NorbertKocsis

### CODE REVIEW

**Comment by lipusz** [comment]
Rebased

**Comment by lipusz** [comment]
Hey Marcellus,

Have you managed to review this? Please, let us know if you had a high load or you were on holiday, so I can forward it to someone else.

Thanks!
-
Tibor

@marcellustavares

**Comment by marcellustavares** [comment]
Just started the review <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-plugins/pull/4696. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Thanks @lipusz and @NorbertKocsis for the fix :)

**Comment by lipusz** [comment]
You're welcome. ;-]

On Thu, Jun 11, 2015 at 3:11 PM, Marcellus Tavares <notifications@github.com
> wrote:

> Thanks @lipusz <https://github.com/lipusz> and @NorbertKocsis
> <https://github.com/NorbertKocsis> for the fix :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marcellustavares/liferay-plugins/pull/293#issuecomment-111127830>
> .
>



-- 

*Tibor LIPUSZ*

Senior Engineer, TS
Security SME, Subscription Services & Release, Global


*Liferay Hungary Kft.* | H-1138 Budapest, Madarász Viktor u. 47. a-b.,
Hungary

 *Visit Us: **www.liferay.com <http://www.liferay.com/>**  |  Like Us:
**facebook.com/liferay
<http://facebook.com/liferay>**  |  Follow Us: twitter.com/liferay
<http://twitter.com/liferay>*


* <http://twitter.com/liferay>*

 <http://www.liferay.com>

**Pull request closed without merging**
