### PR TITLE
LPS-60051

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by yuhai** [comment]
Hi Marcellus,

The issue is from EE customer. And it blocks our progress regarding import KBArticles issues.
 Is it possible that you can review this with a higher priority?

Best Regards,
Hai

**Comment by marcellustavares** [comment]
Sure, I'll push this fwd today. Thanks for letting me know @yuhai

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-plugins/pull/5006. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
