### PR TITLE
LPS-66467 Add StartupAction to create a sample data

### PR DESCRIPTION
**Pull request by inacionery**
https://github.com/brianchandotcom/liferay-portal/pull/40531#issuecomment-224168213

### CODE REVIEW

**Comment by vicnate5** [comment]
@marcellustavares Any update on this pull?

**Comment by marcellustavares** [comment]
Sorry @vicnate5 @inacionery, I missed this. will process this tomorrow.

Thanks

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/vicnate5/liferay-plugins/pull/1. [See changes here.](https://github.com/marcellustavares/liferay-plugins/compare/057adf1~1...057adf1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
