### PR TITLE
LPS-31981

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@marcellustavares sending this one back to you, perhaps should go back to @dacousalr to retest.

Basically, we should be running the getPooledActorIds through all the configured TraskAssignmentSelectors, not just the scripted one to get an accurate list of available userIds to assign to.

There is a usability item here: right now we are returning all userIds.  I think it might be better to return both userId and roleIds.  This way we can re-assign to a role instead of only users as well.

**Comment by dacousalr** [comment]
Hi @marcellustavares, @mhan810,

I have re-tested this successfully. About the usability item, I think it would be better to deal with it in a different LPS.

What do you think?

**Comment by marcellustavares** [comment]
sounds good @dacousalr! will push this fwd then.

thanks

**Comment by marcellustavares** [comment]
Just started the review <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-plugins/pull/4750. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
